import React from 'react';
import { FiInfo } from 'react-icons/fi';

interface AIDisclaimerProps {
  className?: string;
}

export default function AIDisclaimer({ className = '' }: AIDisclaimerProps) {
  return (
    <div className={`flex items-start gap-2 text-[11px] leading-snug text-gray-500 ${className}`}>
      <FiInfo size={12} className="mt-[2px] text-emerald-600" aria-hidden="true" />
      <p>
        The suggestions and analysis in this app are generated by artificial intelligence and are not a substitute for professional medical advice, diagnosis, or treatment. Always consult a qualified health provider with any questions regarding your health or diet.
      </p>
    </div>
  );
}
